export const kpi_group_hours = [
    {
        group: 'HCI_07',
        date: '2021-05-29',
        data: [
            {name: "Công", hour: '8h', amount: 0},
            {name: "Công", hour: '9h', amount: 23},
            {name: "Công", hour: '10h', amount: 24},
            {name: "Công", hour: '11h', amount: 22},
            {name: "Công", hour: '12h', amount: 25},
            {name: "Công", hour: '14h', amount: 21},
            {name: "Công", hour: '15h', amount: 24},
            {name: "Công", hour: '16h', amount: 22},
            {name: "Công", hour: '17h', amount: 21},
            {name: "Luật", hour: '8h', amount: 0},
            {name: "Luật", hour: '9h', amount: 20},
            {name: "Luật", hour: '10h', amount: 21},
            {name: "Luật", hour: '11h', amount: 17},
            {name: "Luật", hour: '12h', amount: 12},
            {name: "Luật", hour: '14h', amount: 22},
            {name: "Luật", hour: '15h', amount: 20},
            {name: "Luật", hour: '16h', amount: 23},
            {name: "Luật", hour: '17h', amount: 21},
            {name: "Hiếu", hour: '8h', amount: 0},
            {name: "Hiếu", hour: '9h', amount: 18},
            {name: "Hiếu", hour: '10h', amount: 22},
            {name: "Hiếu", hour: '11h', amount: 24},
            {name: "Hiếu", hour: '12h', amount: 19},
            {name: "Hiếu", hour: '14h', amount: 12},
            {name: "Hiếu", hour: '15h', amount: 24},
            {name: "Hiếu", hour: '16h', amount: 20},
            {name: "Hiếu", hour: '17h', amount: 21},
            {name: "Đô", hour: '8h', amount: 0},
            {name: "Đô", hour: '9h', amount: 19},
            {name: "Đô", hour: '10h', amount: 21},
            {name: "Đô", hour: '11h', amount: 22},
            {name: "Đô", hour: '12h', amount: 23},
            {name: "Đô", hour: '14h', amount: 19},
            {name: "Đô", hour: '15h', amount: 25},
            {name: "Đô", hour: '16h', amount: 22},
            {name: "Đô", hour: '17h', amount: 20},
        ],
    },
    {
        group: 'HCI_08',
        date: '2021-05-29',
        data: [
            {name: "Hiếu", hour: '8h', amount: 0},
            {name: "Hiếu", hour: '9h', amount: 25},
            {name: "Hiếu", hour: '10h', amount: 29},
            {name: "Hiếu", hour: '11h', amount: 24},
            {name: "Hiếu", hour: '12h', amount: 25},
            {name: "Hiếu", hour: '14h', amount: 27},
            {name: "Hiếu", hour: '15h', amount: 30},
            {name: "Hiếu", hour: '16h', amount: 20},
            {name: "Hiếu", hour: '17h', amount: 21},
            {name: "Q.Anh", hour: '8h', amount: 0},
            {name: "Q.Anh", hour: '9h', amount: 20},
            {name: "Q.Anh", hour: '10h', amount: 21},
            {name: "Q.Anh", hour: '11h', amount: 17},
            {name: "Q.Anh", hour: '12h', amount: 12},
            {name: "Q.Anh", hour: '14h', amount: 22},
            {name: "Q.Anh", hour: '15h', amount: 20},
            {name: "Q.Anh", hour: '16h', amount: 23},
            {name: "Q.Anh", hour: '17h', amount: 21},
            {name: "Lâm", hour: '8h', amount: 0},
            {name: "Lâm", hour: '9h', amount: 18},
            {name: "Lâm", hour: '10h', amount: 22},
            {name: "Lâm", hour: '11h', amount: 24},
            {name: "Lâm", hour: '12h', amount: 19},
            {name: "Lâm", hour: '14h', amount: 12},
            {name: "Lâm", hour: '15h', amount: 24},
            {name: "Lâm", hour: '16h', amount: 20},
            {name: "Lâm", hour: '17h', amount: 21},
            {name: "N.Ánh", hour: '8h', amount: 0},
            {name: "N.Ánh", hour: '9h', amount: 19},
            {name: "N.Ánh", hour: '10h', amount: 21},
            {name: "N.Ánh", hour: '11h', amount: 22},
            {name: "N.Ánh", hour: '12h', amount: 23},
            {name: "N.Ánh", hour: '14h', amount: 19},
            {name: "N.Ánh", hour: '15h', amount: 25},
            {name: "N.Ánh", hour: '16h', amount: 22},
            {name: "N.Ánh", hour: '17h', amount: 20},
        ],
    },
];

export const kpi_group_months = [
    {
        group: 'HCI_07',
        data: [
            {
                name: 'Hệ thống đánh giá',
                month: 1,
                kpi: 18.9,
            },
            {
                name: 'Hệ thống đánh giá',
                month: 2,
                kpi:20.9,
            },
            {
                name: 'Hệ thống đánh giá',
                month: 3,
                kpi: 28.9,
            },
            {
                name: 'Hệ thống đánh giá',
                month: 4,
                kpi: 38.9,
            },
            {
                name: 'Hệ thống đánh giá',
                month: 5,
                kpi: 48.9,
            },
            {
                name: 'Tự đánh giá',
                month: 1,
                kpi: 28.9,
            },
            {
                name: 'Tự đánh giá',
                month: 2,
                kpi: 29.9,
            },
            {
                name: 'Tự đánh giá',
                month: 3,
                kpi: 32.9,
            },
            {
                name: 'Tự đánh giá',
                month: 4,
                kpi: 33.9,
            },
            {
                name: 'Tự đánh giá',
                month: 5,
                kpi: 35.9,
            },
            {
                name: 'Quản lí đánh giá',
                month: 1,
                kpi: 12.4,
            },
            {
                name: 'Quản lí đánh giá',
                month: 2,
                kpi: 16.4,
            },
            {
                name: 'Quản lí đánh giá',
                month: 3,
                kpi: 24.4,
            },
            {
                name: 'Quản lí đánh giá',
                month: 4,
                kpi: 29.4,
            },
            {
                name: 'Quản lí đánh giá',
                month: 5,
                kpi: 30.4,
            },
        ]
    }
];

export const kpi_actors = [
    {
        user_id: 1,
        data: [
            {month: '1', amount: 200},
            {month: '2', amount: 230},
            {month: '3', amount: 110},
            {month: '4', amount: 250},
            {month: '5', amount: 199},
        ]
    },
    {
        user_id: 2,
        data: [
            {month: '1', amount: 200},
            {month: '2', amount: 230},
            {month: '3', amount: 110},
            {month: '4', amount: 250},
            {month: '5', amount: 199},
        ]
    }
];

export const kpi_prdline = [
    {
        code: '1248v32',
        data: [
            {name: "Công", hour: '8h', amount: 0},
            {name: "Công", hour: '9h', amount: 23},
            {name: "Công", hour: '10h', amount: 24},
            {name: "Công", hour: '11h', amount: 22},
            {name: "Công", hour: '12h', amount: 25},
            {name: "Công", hour: '14h', amount: 21},
            {name: "Công", hour: '15h', amount: 24},
            {name: "Công", hour: '16h', amount: 22},
            {name: "Công", hour: '17h', amount: 21},
            {name: "Luật", hour: '8h', amount: 0},
            {name: "Luật", hour: '9h', amount: 20},
            {name: "Luật", hour: '10h', amount: 21},
            {name: "Luật", hour: '11h', amount: 17},
            {name: "Luật", hour: '12h', amount: 12},
            {name: "Luật", hour: '14h', amount: 22},
            {name: "Luật", hour: '15h', amount: 20},
            {name: "Luật", hour: '16h', amount: 23},
            {name: "Luật", hour: '17h', amount: 21},
            {name: "Hiếu", hour: '8h', amount: 0},
            {name: "Hiếu", hour: '9h', amount: 18},
            {name: "Hiếu", hour: '10h', amount: 22},
            {name: "Hiếu", hour: '11h', amount: 24},
            {name: "Hiếu", hour: '12h', amount: 39},
            {name: "Hiếu", hour: '14h', amount: 12},
            {name: "Hiếu", hour: '15h', amount: 24},
            {name: "Hiếu", hour: '16h', amount: 40},
            {name: "Hiếu", hour: '17h', amount: 21},
            {name: "Đô", hour: '8h', amount: 0},
            {name: "Đô", hour: '9h', amount: 19},
            {name: "Đô", hour: '10h', amount: 21},
            {name: "Đô", hour: '11h', amount: 22},
            {name: "Đô", hour: '12h', amount: 26},
            {name: "Đô", hour: '14h', amount: 19},
            {name: "Đô", hour: '15h', amount: 25},
            {name: "Đô", hour: '16h', amount: 22},
            {name: "Đô", hour: '17h', amount: 20},
            {name: "H.Hiếu", hour: '8h', amount: 0},
            {name: "H.Hiếu", hour: '9h', amount: 25},
            {name: "H.Hiếu", hour: '10h', amount: 29},
            {name: "H.Hiếu", hour: '11h', amount: 24},
            {name: "H.Hiếu", hour: '12h', amount: 25},
            {name: "H.Hiếu", hour: '14h', amount: 27},
            {name: "H.Hiếu", hour: '15h', amount: 30},
            {name: "H.Hiếu", hour: '16h', amount: 20},
            {name: "H.Hiếu", hour: '17h', amount: 21},
            {name: "Q.Anh", hour: '8h', amount: 0},
            {name: "Q.Anh", hour: '9h', amount: 20},
            {name: "Q.Anh", hour: '10h', amount: 21},
            {name: "Q.Anh", hour: '11h', amount: 17},
            {name: "Q.Anh", hour: '12h', amount: 12},
            {name: "Q.Anh", hour: '14h', amount: 22},
            {name: "Q.Anh", hour: '15h', amount: 20},
            {name: "Q.Anh", hour: '16h', amount: 23},
            {name: "Q.Anh", hour: '17h', amount: 21},
            {name: "Lâm", hour: '8h', amount: 0},
            {name: "Lâm", hour: '9h', amount: 18},
            {name: "Lâm", hour: '10h', amount: 22},
            {name: "Lâm", hour: '11h', amount: 24},
            {name: "Lâm", hour: '12h', amount: 19},
            {name: "Lâm", hour: '14h', amount: 12},
            {name: "Lâm", hour: '15h', amount: 24},
            {name: "Lâm", hour: '16h', amount: 20},
            {name: "Lâm", hour: '17h', amount: 21},
            {name: "N.Ánh", hour: '8h', amount: 0},
            {name: "N.Ánh", hour: '9h', amount: 19},
            {name: "N.Ánh", hour: '10h', amount: 21},
            {name: "N.Ánh", hour: '11h', amount: 22},
            {name: "N.Ánh", hour: '12h', amount: 23},
            {name: "N.Ánh", hour: '14h', amount: 19},
            {name: "N.Ánh", hour: '15h', amount: 25},
            {name: "N.Ánh", hour: '16h', amount: 22},
            {name: "N.Ánh", hour: '17h', amount: 20},
        ]
    }
];
